name = "ih-scout-worker"
main = "src/worker.ts"
compatibility_date = "2025-04-01"

[observability]
enabled = true

routes = [{ pattern = "scout.insighthunter.app/*", zone_name = "insighthunter.app" }]
