name = "insighthunter-pbx"
main = "src/backend/index.ts"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
APP_NAME = "insighthunter-pbx"
ENVIRONMENT = "development"

[dev]
inspector_port = 9243

[[d1_databases]]
binding = "DB"
database_name = "insighthunter-pbx"
database_id = "3356277c-70d7-4c39-88ea-1cfe26bdbd44"
migrations_dir = "migrations"
