name = "insighthunter-pbx"
main = "src/index.ts"
compatibility_date = "2025-11-01"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "PBX_ROOM", class_name = "PBXRoom", script_name = "insighthunter-pbx" }
]

[[migrations]]
tag = "v1"
new_classes = ["PBXRoom"]

[[d1_databases]]
binding = "DB"
database_name = "insighthunter-pbx"
database_id = "ed35a395-88e3-4015-8b65-68a44973ea74"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "CALL_STATE"
id = "367a7407a51c4a049191d2c67675e032"

[vars]
ENVIRONMENT = "production"

[env.preview]
name = "insighthunter-pbx-preview"

[env.preview.vars]
ENVIRONMENT = "preview"
