name = "insighthunter-auth"
main = "src/index.ts"
compatibility_date = "2025-03-07"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "SESSIONS"
id = "60e34ba310ca40c79edec05470c7a271"

[[kv_namespaces]]
binding = "REFRESH_TOKENS"
id = "ba8d224a437949969d990db3aef71a87"

[[d1_databases]]
binding = "DB"
database_name = "insighthunter-auth"
database_id = "36b4a6b7-3509-4cd2-9cdc-7a35990affd5"

[vars]
JWT_SECRET = "your-secret-here"
SITE_URL = "https://insighthunter.app"