name = "insighthunter-tenant"
main = "src/index.ts"
compatibility_date = "2026-06-20"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "insighthunter-main"
database_id = "04854880-81f5-4c02-b555-905a34492b92"

[vars]
ENVIRONMENT = "production"
PUBLIC_APP_URL = "https://insighthunter.app"
AUTH_URL = "https://auth.insighthunter.app"
