import { Hono } from 'hono';
import { cors } from 'hono/cors';
import puppeteer from '@cloudflare/puppeteer';

interface Env {
  DB: D1Database;
  REPORTS: R2Bucket;
  BROWSER: Fetcher;
  ANALYTICS: AnalyticsEngineDataset;
  AUTH_WORKER_URL: string;
  APP_URL: string;
}

function ok<T>(data: T, status = 200) { return Response.json({ success: true, data }, { status }); }
function err(error: string, status = 400) { return Response.json({ success: false, error }, { status }); }

async function getSession(req: Request, env: Env) {
  const token = req.headers.get('Authorization')?.slice(7);
  if (!token) return null;
  const res = await fetch(`${env.AUTH_WORKER_URL}/verify`, {
    method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token }),
  });
  if (!res.ok) return null;
  const body = await res.json() as { success: boolean; data: { userId: string; orgId: string; tier: string } };
  return body.success ? body.data : null;
}

// ── HTML report template ─────────────────────────────────────────────────────
function buildReportHTML(type: string, org: string, data: unknown[]): string {
  const rows = (data as Record<string, unknown>[]).map(r =>
    `<tr>${Object.values(r).map(v => `<td>${v}</td>`).join('')}</tr>`
  ).join('');
  const headers = data.length > 0 ? Object.keys(data[0] as object).map(k => `<th>${k}</th>`).join('') : '';

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body { font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; color: #28251d; background: #fff; }
  h1   { font-size: 24px; margin-bottom: 4px; }
  p.sub{ color: #7a7974; font-size: 13px; margin-bottom: 32px; }
  table{ width: 100%; border-collapse: collapse; font-size: 13px; }
  th   { background: #f5f3ef; padding: 8px 12px; text-align: left; border-bottom: 1px solid #dcd9d5; }
  td   { padding: 7px 12px; border-bottom: 1px solid #edeae5; }
  tr:last-child td { border-bottom: none; }
  .footer { margin-top: 40px; font-size: 11px; color: #bab9b4; }
</style>
</head><body>
<h1>${type} Report</h1>
<p class="sub">Organization: ${org} &nbsp;·&nbsp; Generated: ${new Date().toLocaleDateString('en-US', { year:'numeric',month:'long',day:'numeric' })}</p>
<table><thead><tr>${headers}</tr></thead><tbody>${rows}</tbody></table>
<div class="footer">Generated by Insight Hunter · insighthunter.app</div>
</body></html>`;
}

const app = new Hono<{ Bindings: Env }>();
app.use('*', cors({ origin: ['https://insighthunter.app', 'http://localhost:4321'] }));

// ── Generate report ──────────────────────────────────────────────────────────
app.post('/generate', async c => {
  const session = await getSession(c.req.raw, c.env);
  if (!session) return err('Unauthorized', 401);

  const { type = 'pl', period = 'month' } = await c.req.json<{ type?: string; period?: string }>();
  const validTypes = ['pl', 'cashflow', 'transactions', 'kpi'];
  if (!validTypes.includes(type)) return err(`type must be one of: ${validTypes.join(', ')}`);

  // Fetch org name
  const org = await c.env.DB.prepare('SELECT name FROM orgs WHERE id = ?').bind(session.orgId).first<{ name: string }>();

  // Build report data from D1
  let data: unknown[] = [];
  if (type === 'pl' || type === 'cashflow') {
    const interval = period === 'year' ? '-12 months' : '-6 months';
    const { results } = await c.env.DB.prepare(`
      SELECT strftime('%Y-%m', date) as Month,
             ROUND(SUM(CASE WHEN type='credit' THEN amount ELSE 0 END),2) as Revenue,
             ROUND(SUM(CASE WHEN type='debit'  THEN amount ELSE 0 END),2) as Expenses,
             ROUND(SUM(CASE WHEN type='credit' THEN amount ELSE -amount END),2) as "Net Income"
      FROM transactions WHERE org_id = ? AND date >= date('now', ?)
      GROUP BY Month ORDER BY Month
    `).bind(session.orgId, interval).all();
    data = results;
  } else if (type === 'transactions') {
    const { results } = await c.env.DB.prepare(
      'SELECT date as Date, description as Description, type as Type, ROUND(amount,2) as Amount, category as Category FROM transactions WHERE org_id = ? ORDER BY date DESC LIMIT 500'
    ).bind(session.orgId).all();
    data = results;
  } else if (type === 'kpi') {
    const { results } = await c.env.DB.prepare(`
      SELECT strftime('%Y-%m', date) as Month,
             ROUND(SUM(CASE WHEN type='credit' THEN amount ELSE 0 END),2) as Revenue,
             ROUND(SUM(CASE WHEN type='debit'  THEN amount ELSE 0 END),2) as Expenses,
             COUNT(*) as Transactions
      FROM transactions WHERE org_id = ? AND date >= date('now', '-12 months')
      GROUP BY Month ORDER BY Month
    `).bind(session.orgId).all();
    data = results;
  }

  if (data.length === 0) return err('No data found for the selected period', 422);

  // Render HTML → PDF via Browser Rendering
  const html = buildReportHTML(type.toUpperCase(), org?.name ?? session.orgId, data);
  const browser = await puppeteer.launch(c.env.BROWSER);
  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: 'networkidle0' });
  const pdfBuffer = await page.pdf({ format: 'A4', margin: { top: '0', right: '0', bottom: '0', left: '0' }, printBackground: true });
  await browser.close();

  // Store in R2
  const reportId = crypto.randomUUID();
  const key = `${session.orgId}/${type}_${period}_${reportId}.pdf`;
  await c.env.REPORTS.put(key, pdfBuffer, { httpMetadata: { contentType: 'application/pdf' } });

  // Record in D1
  await c.env.DB.prepare(
    'INSERT INTO reports (id, org_id, type, period, r2_key, created_at) VALUES (?, ?, ?, ?, ?, ?)'
  ).bind(reportId, session.orgId, type, period, key, new Date().toISOString()).run();

  c.env.ANALYTICS.writeDataPoint({ blobs: ['report_generated', type], indexes: [session.orgId] });
  return ok({ reportId, key, rows: data.length }, 201);
});

// ── List reports ─────────────────────────────────────────────────────────────
app.get('/reports', async c => {
  const session = await getSession(c.req.raw, c.env);
  if (!session) return err('Unauthorized', 401);
  const { results } = await c.env.DB.prepare(
    'SELECT id, type, period, created_at FROM reports WHERE org_id = ? ORDER BY created_at DESC LIMIT 20'
  ).bind(session.orgId).all();
  return ok(results);
});

// ── Download report (signed R2 URL) ─────────────────────────────────────────
app.get('/reports/:id/download', async c => {
  const session = await getSession(c.req.raw, c.env);
  if (!session) return err('Unauthorized', 401);

  const row = await c.env.DB.prepare('SELECT r2_key FROM reports WHERE id = ? AND org_id = ?')
    .bind(c.req.param('id'), session.orgId).first<{ r2_key: string }>();
  if (!row) return err('Report not found', 404);

  const obj = await c.env.REPORTS.get(row.r2_key);
  if (!obj) return err('File not found in storage', 404);

  return new Response(obj.body, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${row.r2_key.split('/').pop()}"`,
    },
  });
});

// ── Delete report ────────────────────────────────────────────────────────────
app.delete('/reports/:id', async c => {
  const session = await getSession(c.req.raw, c.env);
  if (!session) return err('Unauthorized', 401);

  const row = await c.env.DB.prepare('SELECT r2_key FROM reports WHERE id = ? AND org_id = ?')
    .bind(c.req.param('id'), session.orgId).first<{ r2_key: string }>();
  if (!row) return err('Report not found', 404);

  await Promise.all([
    c.env.REPORTS.delete(row.r2_key),
    c.env.DB.prepare('DELETE FROM reports WHERE id = ?').bind(c.req.param('id')).run(),
  ]);
  return ok({ deleted: true });
});

export default app;
