name = "insight-platform-dispatch"
main = "src/index.ts"
compatibility_date = "2025-03-07"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

[[routes]]
pattern = "api.insighthunter.com/api/*"
zone_name = "insighthunter.com"

[[dispatch_namespaces]]
binding = "DISPATCHER"
namespace = "insight-users"

[[d1_databases]]
binding = "PLATFORM_DB"
database_name = "insight-platform-db"
database_id = "fe51ad9c-c08b-4fe4-9c0a-67361d9f2c09"

[[kv_namespaces]]
binding = "ROUTING_CACHE"
id = "a9db8755115f44048b7d334c42a999e5"

[[analytics_engine_datasets]]
binding = "EVENTS"
dataset = "insight_api_events"

[vars]
CF_ACCOUNT_ID = "18c8e61a3669253dcfd0c7eec6be36a3"