// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-layouts/FullViewport.tsx": () => import("../components/mockups/homepage-layouts/FullViewport.tsx"),
  "./components/mockups/homepage-layouts/SidebarNav.tsx": () => import("../components/mockups/homepage-layouts/SidebarNav.tsx"),
  "./components/mockups/homepage-layouts/SplitHero.tsx": () => import("../components/mockups/homepage-layouts/SplitHero.tsx"),
  "./components/mockups/homepage-usability/AffordanceFirst.tsx": () => import("../components/mockups/homepage-usability/AffordanceFirst.tsx"),
  "./components/mockups/homepage-usability/HierarchyFirst.tsx": () => import("../components/mockups/homepage-usability/HierarchyFirst.tsx"),
  "./components/mockups/homepage-vibes/BoldElectric.tsx": () => import("../components/mockups/homepage-vibes/BoldElectric.tsx"),
  "./components/mockups/homepage-vibes/CleanMinimal.tsx": () => import("../components/mockups/homepage-vibes/CleanMinimal.tsx"),
  "./components/mockups/homepage-vibes/WarmHuman.tsx": () => import("../components/mockups/homepage-vibes/WarmHuman.tsx")
};
