name = "insighthunter-ledger"
main = "src/index.ts"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
APP_NAME = "insighthunter-ledger"
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "insighthunter-ledger"
database_id = "8dc66f6a-da61-4421-a092-a4845fc0db8d"

[[routes]]
pattern = "ledger.insighthunter.app/*"
zone_name = "insighthunter.app"
